### ISSUE TITLE
Highlight own vaadin-messages from others

### ISSUE THREAD

**Issue by juuso-vaadin** [vaadin/collaboration-engine#30] opened 2021-05-03 06:46 UTC
**Is your feature request related to a use case? Please describe.**
In vaadin-message-list, I would like to be able to style my own messages to be different from other messages.

**Describe the solution you'd like**
There should be an easy way to apply custom styling to certain messages. This could be done by introducing an attribute to vaadin-message.

**Additional context**
![image](https://user-images.githubusercontent.com/19607782/116847689-b9f25080-abf3-11eb-9f9c-66eab4238eb2.png)

**Comment by jouni** [comment] 2021-05-03 06:51
The same feature could also be used to distinguish “system messages” from messages from end users.

**Comment by Peppe** [comment] 2021-05-03 09:51
Agreed. I think this could be called something like "source" or "origin". We should still separate "me" and "system" so that they can be handled separately, as both can have separate visuals and separate features (delete, edit..)

Thoughts on how this could be implemented. Names can be debated:
1. Add a new property to <vaadin-message> called "origin". Recognized values would be "me", "system" and "others". "others" would be the default if nothing is configured.
2. Add the origin property to the json format that <vaadin-message-list>'s input property takes in.
3. CollaborationMessageList would automatically add "origin=me" on those messages that has the same userName as the currentUser attached to the list.

**Comment by anezthes** [comment] 2021-05-03 10:30
I can write the CSS for that on Wednesday.

Semi-related: we have a PR for 'system' messages here:
> https://github.com/vaadin/vaadin-messages/pull/47/files

Just CSS though.

**Comment by jouni** [comment] 2021-05-03 13:20
My initial thought was to add support for setting a `theme` attribute value for individual message components. Basically the same as what Jens suggested, but avoiding a new concept of “origin”.

**Comment by pekam** [comment] 2021-05-24 13:50
We concluded with @anezthes that we should not set any theme variant to own messages by default. Highlighting your own messages looks good only with a theme that has "bubbles" around the content, like in the screenshot in this ticket. Our message components are similar to Slack and Discord, where there's also no highlight for own messages.

Any custom theme variant can still be added to own messages with the new message configurator API:
```java
collaborationMessageList.setMessageConfigurator((message, user) -> {
    if (user.equals(localUser)) {
        message.addThemeNames("outbound");
    }
});
```

**Comment by pekam** [comment] 2021-05-24 13:53
The issue is resolved with the following PRs:
1. https://github.com/vaadin/web-components/pull/372 add theme property to vaadin-message-list items
2. https://github.com/vaadin/flow-components/pull/979 add theme API to MessageListItem
3. https://github.com/vaadin/collaboration-engine-internal/pull/588 add MessageConfigurator API

**Closed by pekam** 2021-05-24 13:53 UTC
Labels: enhancement

**Comment by pekam** [comment] 2021-05-25 13:41
I opened a new ticket for providing Lumo theme variants out of the box: https://github.com/vaadin/web-components/issues/1994
